// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bijzqompuhwqzbryassj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpanpxb21wdWh3cXpicnlhc3NqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3ODQ3MTYsImV4cCI6MjA2MDM2MDcxNn0.1Q4lCpKUAQ37Bzuvf4VcUpfS39lmdyuIVx9nRYWkcXg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);